### ISSUE TITLE
Remove src/main/java/com/google/sps/data/Info.java

### ISSUE THREAD

**Issue by changlingh** [habit-stackers/app#7]
I believe [src/main/java/com/google/sps/data/Info.java](https://github.com/habit-stackers/app/commit/8522a6542b6926f3227a91325dab1e4259b99b96#diff-b3112d462428ce9ff1956aee4aa6680b177870fc676ebb7deb35cf0d655b5e70) was left over from the datastore library exercise.

**Comment by jessy413** [comment]
Done.
